// <auto-generated />
namespace FixingIT.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Init_New_Db_20130621_Kl001000 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_New_Db_20130621_Kl001000));
        
        string IMigrationMetadata.Id
        {
            get { return "201306202213250_Init_New_Db_20130621_Kl001000"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
